Repository DIT113-V22/group-09, pull requests merged in 2022-05, with the labels that each got.

#46 Add improved GUI
  arduino/smartcar/smartcar.ino
  gui/pom.xml
  gui/src/main/java/app/App.java
  gui/src/main/java/app/CarGUI.java
  gui/src/main/java/app/Controller.java
  gui/src/main/java/app/KeyboardHandler.java
  gui/src/main/java/app/MovementHandler.java
  gui/src/main/java/controllers/StartController.java
  gui/src/main/java/controllers/SteeringController.java
  gui/src/main/java/models/User.java
  gui/src/main/java/util/TxtWriter.java
  gui/src/main/java/util/ValidityChecker.java
  gui/src/main/java/util/VarargFunctions.java
  gui/src/main/resources/img/Loading.jpg
  gui/src/main/resources/pic320.png
  gui/src/main/resources/profiles/profiles.txt
  gui/src/main/resources/stylesheets/defaultTheme.css
  gui/src/main/resources/stylesheets/tabs.css
  gui/src/main/resources/ui.fxml
  gui/src/main/resources/views/start-view.fxml
  gui/src/main/resources/views/steering-view.fxml
  javaCarAPI/pom.xml
  javaCarAPI/src/main/java/api/CarAPI.java
  javaCarAPI/src/main/java/api/state/CommandState.java
  javaCarAPI/src/main/java/api/state/VehicleState.java
  languageprocessing/src/main/java/commands_processing/Command.java
  languageprocessing/src/main/java/commands_processing/InputProcessor.java
  languageprocessing/src/main/java/file_processing/FileLoader.java
  languageprocessing/src/test/java/grammar/TextTranslatorTest.java
Labels: Sprint 2

#52 Expand language translation functionality
  languageprocessing/src/main/java/commands_processing/Command.java
  languageprocessing/src/main/java/commands_processing/CommandBuilder.java
  languageprocessing/src/main/java/grammar/LanguageEnums.java
  languageprocessing/src/main/java/grammar/LanguageMaps.java
  languageprocessing/src/main/java/grammar/OmittanceInferer.java
  languageprocessing/src/main/resources/files/actions_map.txt
  languageprocessing/src/main/resources/files/clause_dividers_list.txt
  languageprocessing/src/main/resources/files/inferDirFromAct_map.txt
  languageprocessing/src/main/resources/files/inferUnitFromAct_map.txt
  languageprocessing/src/main/resources/files/phrasal_verbs_list.txt
  languageprocessing/src/test/java/grammar/TextTranslatorTest.java
Labels: Sprint 2

#54 #50 Add visually appealing GUI
  gui/src/main/java/app/App.java
  gui/src/main/java/app/CarGUI.java
  gui/src/main/java/app/Controller.java
  gui/src/main/java/controllers/StartController.java
  gui/src/main/java/controllers/SteeringController.java
  gui/src/main/resources/img/bg.jpg
  gui/src/main/resources/stylesheets/defaultTheme.css
  gui/src/main/resources/stylesheets/tabs.css
  gui/src/main/resources/ui.fxml
  gui/src/main/resources/views/start-view.fxml
  gui/src/main/resources/views/steering-view.fxml
  languageprocessing/src/main/java/commands_processing/CommandParser.java
  languageprocessing/src/main/java/grammar/PhrasalVerbChecker.java
Labels: Sprint 3

#59 Improve car movement accuracy
  arduino/smartcar/smartcar.ino
Labels: Sprint 3

#62 Emergency check fix
  arduino/smartcar/smartcar.ino
Labels: bug, Sprint 4

#63 Finish GUI
  gui/src/main/java/app/CarGUI.java
  gui/src/main/java/controllers/StartController.java
  gui/src/main/java/controllers/SteeringController.java
  gui/src/main/java/enums/Languages.java
  gui/src/main/java/enums/S1Headers.java
  gui/src/main/java/util/TxtWriter.java
  gui/src/main/java/util/VarargFunctions.java
  gui/src/main/resources/img/Loading.jpg
  gui/src/main/resources/img/Loading2.jpg
  gui/src/main/resources/img/bg1.png
  gui/src/main/resources/languages/current/head_s1.txt
  gui/src/main/resources/languages/current/pTxt_s1.txt
  gui/src/main/resources/languages/current/s1.txt
  gui/src/main/resources/languages/current/s2.txt
  gui/src/main/resources/languages/english/head_s1.txt
  gui/src/main/resources/languages/english/pTxt_s1.txt
  gui/src/main/resources/languages/english/s1.txt
  gui/src/main/resources/languages/english/s2.txt
  gui/src/main/resources/languages/korean/head_s1.txt
  gui/src/main/resources/languages/korean/pTxt_s1.txt
  gui/src/main/resources/languages/korean/s1.txt
  gui/src/main/resources/languages/korean/s2.txt
  gui/src/main/resources/languages/persian/head_s1.txt
  gui/src/main/resources/languages/persian/pTxt_s1.txt
  gui/src/main/resources/languages/persian/s1.txt
  gui/src/main/resources/languages/persian/s2.txt
  gui/src/main/resources/languages/polish/head_s1.txt
  gui/src/main/resources/languages/polish/pTxt_s1.txt
  gui/src/main/resources/languages/polish/s1.txt
  gui/src/main/resources/languages/polish/s2.txt
  gui/src/main/resources/languages/swedish/head_s1.txt
  gui/src/main/resources/languages/swedish/pTxt_s1.txt
  gui/src/main/resources/languages/swedish/s1.txt
  gui/src/main/resources/languages/swedish/s2.txt
  gui/src/main/resources/stylesheets/defaultTheme.css
  gui/src/main/resources/stylesheets/tabs.css
  gui/src/main/resources/views/start-view.fxml
  gui/src/main/resources/views/steering-view.fxml
  javaCarAPI/src/main/java/api/CarAPI.java
  languageprocessing/src/main/java/commands_processing/CommandBuilder.java
  languageprocessing/src/main/java/commands_processing/CommandParser.java
  languageprocessing/src/main/java/file_processing/FileLoader.java
  languageprocessing/src/main/java/grammar/LanguageMaps.java
  languageprocessing/src/main/java/grammar/OmittanceInferer.java
  languageprocessing/src/main/java/grammar/PhrasalVerbChecker.java
  languageprocessing/src/main/java/grammar/TextTranslator.java
  languageprocessing/src/main/java/grammar/TextUnifier.java
  languageprocessing/src/main/java/settings/FilePaths.java
  languageprocessing/src/main/resources/files/rotations_map.txt
  languageprocessing/src/main/resources/files/shapes_map.txt
  languageprocessing/src/test/java/grammar/TextTranslatorTest.java
Labels: Sprint 4

#65 Add finished map info and link
  mapInfo.txt
Labels: Sprint 4

#68 Add Coordinate Functionality
  .github/workflows/language-tests.yml
  CarPath/pom.xml
  CarPath/src/main/java/coordinates/Coordinate.java
  CarPath/src/main/java/coordinates/CoordinateController.java
  arduino/smartcar/smartcar.ino
  gui/src/main/java/controllers/SteeringController.java
  languageprocessing/pom.xml
  languageprocessing/src/main/java/commands_processing/Command.java
  languageprocessing/src/main/java/commands_processing/CommandBuilder.java
  languageprocessing/src/main/java/commands_processing/CommandParser.java
  languageprocessing/src/main/java/commands_processing/InputProcessor.java
  languageprocessing/src/main/java/grammar/LanguageEnums.java
  languageprocessing/src/main/resources/files/actions_map.txt
  languageprocessing/src/main/resources/files/inferAmountFromAct_map.txt
  languageprocessing/src/main/resources/files/inferDirFromAct_map.txt
  languageprocessing/src/main/resources/files/inferUnitFromAct_map.txt
  languageprocessing/src/main/resources/files/unitConversions.txt
  languageprocessing/src/test/java/grammar/TextTranslatorTest.java
Labels: Sprint 4

#70 fix exit bug
  gui/src/main/java/controllers/StartController.java
  gui/src/main/java/controllers/SteeringController.java
Labels: Sprint 4
